---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    role-file: requirements.yml

driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml
platforms:
  - name: zabbix-web-mysql-centos
    image: milcom/centos7-systemd
    privileged: True
    groups:
      - mysql
  - name: zabbix-web-pgsql-centos
    image: milcom/centos7-systemd
    privileged: True
    groups:
      - postgresql
  - name: zabbix-web-mysql-debian
    image: minimum2scp/systemd-stretch
    privileged: True
    command: /sbin/init
    groups:
      - mysql
  - name: zabbix-web-pgsql-debian
    image: minimum2scp/systemd-stretch
    privileged: True
    command: /sbin/init
    groups:
      - postgresql
  - name: zabbix-web-mysql-ubuntu
    image: solita/ubuntu-systemd:latest
    privileged: True
    command: /sbin/init
    groups:
      - mysql
  - name: zabbix-web-pgsql-ubuntu
    image: solita/ubuntu-systemd:latest
    privileged: True
    command: /sbin/init
    groups:
      - postgresql

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      mysql:
        zabbix_server_database: mysql
        zabbix_server_database_long: mysql
        zabbix_server_dbport: 3306
      postgresql:
        zabbix_server_database: pgsql
        zabbix_server_database_long: postgresql
    host_vars:
      zabbix-web-pgsql-debian:
        zabbix_url: zabbix-web-pgsql-debian
        zabbix_websrv_servername: zabbix-web-pgsql-debian
      zabbix-web-mysql-debian:
        zabbix_url: zabbix-web-mysql-debian
        zabbix_websrv_servername: zabbix-web-mysql-debian
      zabbix-web-pgsql-centos:
        zabbix_url: zabbix-web-pgsql-centos
        zabbix_websrv_servername: zabbix-web-pgsql-centos
      zabbix-web-mysql-centos:
        zabbix_url: zabbix-web-mysql-centos
        zabbix_websrv_servername: zabbix-web-mysql-centos
      zabbix-web-mysql-ubuntu:
        zabbix_url: zabbix-web-mysql-ubuntu
        zabbix_websrv_servername: zabbix-web-mysql-ubuntu
      zabbix-web-pgsql-ubuntu:
        zabbix_url: zabbix-web-pgsql-ubuntu
        zabbix_websrv_servername: zabbix-web-pgsql-ubuntu

scenario:
  name: default

verifier:
  name: testinfra
  lint:
    name: flake8
